// File: docs/test-scripts/playwright/clara-reviewer-flow.spec.ts
// Generated by: pm-builder-agent
// Source: QA Findings from Review 407759 (12 findings)
// Date: June 10, 2026
// Framework: Playwright (TypeScript)

import { test, expect, Page } from '@playwright/test';

const REVIEW_URL = 'https://gamma.grc.a2z.com/docs/Review/407759/draft';
const PAGE_LOAD_TIMEOUT = 15000;

// ─────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────

async function waitForClaraContent(page: Page) {
  // Wait for CLARA Insights panel or any "Generated by Clara" label
  await page.waitForSelector('text=Generated by Clara', { timeout: PAGE_LOAD_TIMEOUT });
}

async function getInlineInsightText(page: Page, questionIndex: number): Promise<string> {
  const buttons = await page.locator('button:has-text("CLARA recommendation")').all();
  if (questionIndex >= buttons.length) return '';
  const parent = buttons[questionIndex].locator('..');
  const insight = parent.locator('p:has-text("Insights:")');
  return (await insight.textContent()) || '';
}

async function getRecommendationText(page: Page, questionIndex: number): Promise<string> {
  const buttons = await page.locator('button:has-text("CLARA recommendation")').all();
  if (questionIndex >= buttons.length) return '';
  const btnText = await buttons[questionIndex].textContent();
  const match = btnText?.match(/CLARA\s*recommendation:\s*([\s\S]*?)(?:\s*▾|$)/);
  return match ? match[1].trim() : '';
}

// ─────────────────────────────────────────────────────────────────
// SETUP
// ─────────────────────────────────────────────────────────────────

test.describe('CLARA Reviewer Flow — Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(REVIEW_URL);
    await page.waitForLoadState('networkidle');
    // Wait for page title to confirm review loaded
    await expect(page).toHaveTitle(/Publication/, { timeout: PAGE_LOAD_TIMEOUT });
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #1: "ConfirmationField" jargon leak
  // Source: QA Finding #1, Severity P1
  // ─────────────────────────────────────────────────────────────

  test('Finding-01: No internal field names in user-facing insight text', async ({ page }) => {
    await waitForClaraContent(page);

    // Get Q1 inline insight text
    const insightText = await getInlineInsightText(page, 0);

    // Assert: No CamelCase internal identifiers
    expect(insightText).not.toContain('ConfirmationField');
    expect(insightText).not.toContain('reviewSetId');
    expect(insightText).not.toContain('entityType');
    expect(insightText).not.toContain('complianceFlag');
    expect(insightText).not.toContain('empty array');
  });

  test('Finding-01b: Q1 insight uses "accurate" not "current"', async ({ page }) => {
    await waitForClaraContent(page);

    const insightText = await getInlineInsightText(page, 0);

    // The question asks for "accurate" — insight should reflect this
    // It should NOT say "current" as the primary attestation requirement
    if (insightText.includes('current') && !insightText.includes('accurate')) {
      // Fail: insight says "current" without "accurate"
      expect(insightText).toContain('accurate');
    }
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #2: Frequency discrepancy not flagged inline
  // Source: QA Finding #2, Severity P1
  // ─────────────────────────────────────────────────────────────

  test('Finding-02: Frequency discrepancy flagged at Q1 inline', async ({ page }) => {
    await waitForClaraContent(page);

    // Get control page data
    const controlFrequency = await page.locator('text=Control Frequency').locator('..').textContent();
    const whenPerformed = await page.locator('text=When is the control performed').locator('..').textContent();

    // Detect discrepancy
    const hasMonthly = controlFrequency?.includes('Monthly');
    const hasQuarterly = whenPerformed?.includes('quarterly');

    if (hasMonthly && hasQuarterly) {
      // Discrepancy exists — inline Q1 should flag it
      const q1Insight = await getInlineInsightText(page, 0);
      const hasDiscrepancyFlag = q1Insight.includes('inconsistency') ||
        q1Insight.includes('discrepancy') ||
        q1Insight.includes('Monthly') ||
        q1Insight.includes('quarterly') ||
        q1Insight.includes('⚠️');

      expect(hasDiscrepancyFlag).toBe(true);
    }
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #3: Insight vs Reasoning conflation
  // Source: QA Finding #3, Severity P1
  // ─────────────────────────────────────────────────────────────

  test('Finding-03: Inline insight is NOT identical to Full Analysis reasoning', async ({ page }) => {
    await waitForClaraContent(page);

    // Get Q5 (Design Effectiveness) inline insight
    const inlineInsight = await getInlineInsightText(page, 4); // 0-indexed, Q5 = index 4

    // Open Full Analysis modal
    await page.getByRole('button', { name: 'View Full Analysis' }).click();
    await page.waitForSelector('text=Reasoning:', { timeout: 10000 });

    // Get Full Analysis Reasoning for the same question
    const reasoningElements = await page.locator('text=Reasoning:').all();
    let reasoning = '';
    for (const el of reasoningElements) {
      const parent = el.locator('..');
      const text = await parent.textContent();
      if (text?.includes('detective design') || text?.includes('prior reviews')) {
        reasoning = text.replace('Reasoning:', '').trim();
        break;
      }
    }

    // Close modal
    await page.keyboard.press('Escape');

    // Assert: inline insight should NOT be word-for-word the Reasoning
    if (reasoning && inlineInsight) {
      // Allow partial overlap but not identical
      const isIdentical = inlineInsight.trim() === reasoning.trim();
      expect(isIdentical).toBe(false);
    }
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #4: Q3 recommends "Yes" when 0 attachments
  // Source: QA Finding #4, Severity P0
  // ─────────────────────────────────────────────────────────────

  test('Finding-04: Q3 recommendation reflects actual attachment state', async ({ page }) => {
    await waitForClaraContent(page);

    // Count attachments on the review
    const attachmentHeader = page.locator('text=Files & external link').first();
    const headerText = await attachmentHeader.textContent();
    const countMatch = headerText?.match(/\((\d+)\)/);
    const attachmentCount = countMatch ? parseInt(countMatch[1]) : 0;

    // Get Q3 recommendation (evidence availability)
    const q3Rec = await getRecommendationText(page, 2); // 0-indexed, Q3 = index 2

    // If 0 attachments, recommendation should NOT be unconditional "Yes"
    if (attachmentCount === 0) {
      const isUnconditionalYes = q3Rec === 'Yes';
      expect(isUnconditionalYes).toBe(false);
      // Should be conditional: "Yes (conditional)", "No", or include caveat
    }
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #5: Historical "No" not prominently flagged
  // Source: QA Finding #5, Severity P2
  // ─────────────────────────────────────────────────────────────

  test('Finding-05: Historical effectiveness failure visually flagged at Q6', async ({ page }) => {
    await waitForClaraContent(page);

    // Get Q6 insight (Operating Effectiveness)
    const q6Insight = await getInlineInsightText(page, 5); // index 5

    // If insight mentions a prior "No" answer
    if (q6Insight.includes('No') && q6Insight.includes('2022')) {
      // Should have a visual flag indicator (⚠️ or warning styling)
      const hasVisualFlag = q6Insight.includes('⚠️') ||
        q6Insight.includes('PRIOR') ||
        q6Insight.includes('WARNING') ||
        q6Insight.includes('Flag');

      expect(hasVisualFlag).toBe(true);
    }
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #7: Executive Summary leads with obvious statement
  // Source: QA Finding #7, Severity P2
  // ─────────────────────────────────────────────────────────────

  test('Finding-07: Executive Summary does not lead with obvious page state', async ({ page }) => {
    await waitForClaraContent(page);

    // Get executive summary text
    const summaryEl = page.locator('text=Executive Summary').locator('..');
    const summaryText = await summaryEl.textContent() || '';

    // Extract first sentence
    const firstSentence = summaryText.split('.')[0] || '';

    // Should NOT start with obvious statements
    const obviousPatterns = [
      'All 13 questions are currently blank',
      'This is a fresh draft review',
      'This draft review has 13 questions',
      'questions are blank',
    ];

    for (const pattern of obviousPatterns) {
      expect(firstSentence).not.toContain(pattern);
    }
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #9: IPA Q2 pre-fills completed attestation
  // Source: QA Finding #9, Severity P1
  // ─────────────────────────────────────────────────────────────

  test('Finding-09: IPA attestation recommendation is conditional, not completed', async ({ page }) => {
    await waitForClaraContent(page);

    // Get IPA Q2 recommendation (index 10 — Q11 in sequence)
    const ipaQ2Rec = await getRecommendationText(page, 10);

    if (ipaQ2Rec) {
      // Should NOT read as a completed attestation without conditional framing
      const startsWithCompleted = ipaQ2Rec.startsWith('I reviewed') ||
        ipaQ2Rec.startsWith('I confirmed') ||
        ipaQ2Rec.startsWith('I verified');

      if (startsWithCompleted) {
        // Must include conditional framing
        const hasConditional = ipaQ2Rec.includes('[After') ||
          ipaQ2Rec.includes('conditional') ||
          ipaQ2Rec.includes('before submitting') ||
          ipaQ2Rec.includes('once you have');

        expect(hasConditional).toBe(true);
      }
    }
  });
});
