// File: docs/test-scripts/playwright/clara-approver-flow.spec.ts
// Generated by: pm-builder-agent
// Source: QA Findings from Review 401431 (Approver persona)
// Date: June 10, 2026
// Framework: Playwright (TypeScript)

import { test, expect, Page } from '@playwright/test';

const APPROVER_REVIEW_URL = 'https://gamma.grc.a2z.com/docs/Review/401431/publish';
const PAGE_LOAD_TIMEOUT = 15000;

test.describe('CLARA Approver Flow — Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(APPROVER_REVIEW_URL);
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveTitle(/Publication/, { timeout: PAGE_LOAD_TIMEOUT });
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING A9: No pre-drafted rejection when CLARA identifies issues
  // Source: Approver QA Finding A9, Severity P1
  // ─────────────────────────────────────────────────────────────

  test('Finding-A9: Reject button pre-populates with CLARA findings', async ({ page }) => {
    // Verify CLARA Executive Summary has critical issues
    const insightsText = await page.locator('text=Executive Summary').locator('..').textContent() || '';
    const hasCriticalIssues = insightsText.includes('critical') ||
      insightsText.includes('invalid') ||
      insightsText.includes('test') ||
      insightsText.includes('placeholder');

    if (hasCriticalIssues) {
      // Click "Reject with comment"
      await page.getByRole('button', { name: 'Reject with comment' }).click();
      await page.waitForTimeout(2000);

      // Check if rejection text field is pre-populated
      const textArea = page.locator('textarea').first();
      const prefilledText = await textArea.inputValue();

      // Assert: field should have CLARA-drafted content, not be empty
      expect(prefilledText.length).toBeGreaterThan(0);

      // Assert: pre-filled content references the specific issues CLARA found
      const referencesIssues = prefilledText.includes('evidence') ||
        prefilledText.includes('placeholder') ||
        prefilledText.includes('test file') ||
        prefilledText.includes('contradiction');

      expect(referencesIssues).toBe(true);
    }
  });

  // ─────────────────────────────────────────────────────────────
  // AI Governance: CLARA visible in Submitted state for approver
  // Source: BRD Epic-11 (AI Governance)
  // ─────────────────────────────────────────────────────────────

  test('AI Governance: CLARA insights visible to approver in Submitted state', async ({ page }) => {
    // In Submitted state, approver should see CLARA summary
    const hasClaraContent = await page.locator('text=Generated by Clara').count();
    const hasInsights = await page.locator('text=Executive Summary').count();
    const hasViewFullAnalysis = await page.locator('button:has-text("View Full Analysis")').count();

    // Approver SHOULD see AI content (per BRD: "AI approver-assist allowed")
    expect(hasClaraContent).toBeGreaterThan(0);
    expect(hasInsights).toBeGreaterThan(0);
    expect(hasViewFullAnalysis).toBeGreaterThan(0);
  });

  test('AI Governance: Approve and Reject buttons are present', async ({ page }) => {
    const approveBtn = page.getByRole('button', { name: 'Approve' });
    const rejectBtn = page.getByRole('button', { name: 'Reject with comment' });

    await expect(approveBtn).toBeVisible();
    await expect(rejectBtn).toBeVisible();
  });

  // ─────────────────────────────────────────────────────────────
  // CLARA Assessment panels (Approver-specific UI)
  // ─────────────────────────────────────────────────────────────

  test('Approver view: CLARA assessment panels exist per question', async ({ page }) => {
    // Approver sees "CLARAassessment" expandable panels
    const assessmentPanels = await page.locator('button:has-text("CLARAassessment")').count();

    // Should have multiple assessment panels (one per question)
    expect(assessmentPanels).toBeGreaterThan(0);
  });
});
