// Global setup for Midway authentication
// Generated by: pm-builder-agent
//
// This runs ONCE before all tests. It launches a headed browser,
// navigates to the GRC app (triggering Midway/AEA auth), and saves
// the authenticated session state for all subsequent tests.
//
// PREREQUISITE: Run `mwinit -s` before executing tests.

import { chromium, FullConfig } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const AUTH_STATE_PATH = path.join(__dirname, '.auth', 'midway-state.json');

async function globalSetup(config: FullConfig) {
  // Ensure auth directory exists
  const authDir = path.dirname(AUTH_STATE_PATH);
  if (!fs.existsSync(authDir)) {
    fs.mkdirSync(authDir, { recursive: true });
  }

  // Check if we have a valid saved state (less than 4 hours old)
  if (fs.existsSync(AUTH_STATE_PATH)) {
    const stats = fs.statSync(AUTH_STATE_PATH);
    const ageMs = Date.now() - stats.mtimeMs;
    const fourHoursMs = 4 * 60 * 60 * 1000;

    if (ageMs < fourHoursMs) {
      console.log('Using cached Midway auth state (less than 4 hours old)');
      return;
    }
  }

  console.log('Authenticating with Midway (headed browser)...');
  console.log('If AEA popup appears, approve it in the browser window.');

  // Launch headed browser for auth
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();

  try {
    // Navigate to GRC — triggers Midway redirect
    await page.goto('https://gamma.grc.a2z.com');

    // Wait for successful authentication (URL should be grc.a2z.com, not midway-auth)
    await page.waitForURL('**/grc.a2z.com/**', { timeout: 60000 });

    console.log('Midway authentication successful. Saving state...');

    // Save authenticated state
    await context.storageState({ path: AUTH_STATE_PATH });
  } catch (error) {
    console.error('Midway authentication failed. Ensure:');
    console.error('  1. Run `mwinit -s` in terminal first');
    console.error('  2. AEA browser extension is installed');
    console.error('  3. You have access to gamma.grc.a2z.com');
    throw error;
  } finally {
    await browser.close();
  }
}

export default globalSetup;
