// Playwright configuration for CLARA test scripts
// Generated by: pm-builder-agent

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  fullyParallel: false, // Sequential for stateful review testing
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: 1, // Single worker for Midway auth state
  reporter: [
    ['html', { open: 'never' }],
    ['list'],
  ],

  use: {
    // Base URL for GRC gamma
    baseURL: 'https://gamma.grc.a2z.com',

    // Generous timeouts for internal apps
    actionTimeout: 30000,
    navigationTimeout: 60000,

    // Capture traces on failure
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',

    // Auth state from Midway login
    storageState: '.auth/midway-state.json',
  },

  projects: [
    // Auth setup — run first
    {
      name: 'auth-setup',
      testMatch: /global-setup\.ts/,
    },
    // Main tests
    {
      name: 'clara-tests',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['auth-setup'],
    },
  ],

  // Global setup for Midway authentication
  globalSetup: require.resolve('./global-setup'),
});
