// File: docs/test-scripts/playwright/regression/evidence-validation.spec.ts
// Generated by: pm-builder-agent
// Source: QA Findings #10, #11, #12 (Evidence P0s)
// Date: June 10, 2026
// Framework: Playwright (TypeScript)

import { test, expect, Page } from '@playwright/test';

const REVIEW_URL = 'https://gamma.grc.a2z.com/docs/Review/407759/draft';
const PAGE_LOAD_TIMEOUT = 15000;
const REANALYZE_TIMEOUT = 60000;

test.describe('CLARA Evidence Validation — P0 Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(REVIEW_URL);
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveTitle(/Publication/, { timeout: PAGE_LOAD_TIMEOUT });
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #10: Evidence validation intelligence trapped in Full Analysis
  // Source: QA Finding #10, Severity P0
  // ─────────────────────────────────────────────────────────────

  test('Finding-10: Evidence validation results visible inline (not just Full Analysis)', async ({ page }) => {
    // Check if any attachments exist
    const attachmentHeader = page.locator('h2:has-text("Files & external link")').first();
    const headerText = await attachmentHeader.textContent();
    const countMatch = headerText?.match(/\((\d+)\)/);
    const attachmentCount = countMatch ? parseInt(countMatch[1]) : 0;

    if (attachmentCount > 0) {
      // Open Full Analysis to check if evidence validation ran
      await page.getByRole('button', { name: 'View Full Analysis' }).click();
      await page.waitForTimeout(5000);

      const fullAnalysisText = await page.locator('[class*="modal"], [role="dialog"]').textContent() || '';
      const hasEvidenceValidation = fullAnalysisText.includes('invalid') ||
        fullAnalysisText.includes('not valid evidence') ||
        fullAnalysisText.includes('Confidence') ||
        fullAnalysisText.includes('Missing');

      if (hasEvidenceValidation) {
        // Close modal
        await page.keyboard.press('Escape');
        await page.waitForTimeout(1000);

        // NOW check: the evidence finding should ALSO be visible inline at Q3
        const q3Section = page.locator('button:has-text("CLARA recommendation")').nth(2); // Q3
        const q3Parent = q3Section.locator('..');
        const q3Text = await q3Parent.textContent() || '';

        // Assert: inline Q3 area should reference evidence validity
        const inlineHasEvidenceInfo = q3Text.includes('invalid') ||
          q3Text.includes('not valid') ||
          q3Text.includes('⚠️') ||
          q3Text.includes('evidence issue') ||
          q3Text.includes('replace');

        expect(inlineHasEvidenceInfo).toBe(true);
      }
    }
  });

  test('Finding-10b: Attachment table shows validity indicator', async ({ page }) => {
    const attachmentHeader = page.locator('h2:has-text("Files & external link")').first();
    const headerText = await attachmentHeader.textContent();
    const countMatch = headerText?.match(/\((\d+)\)/);
    const attachmentCount = countMatch ? parseInt(countMatch[1]) : 0;

    if (attachmentCount > 0) {
      // Check attachment table for validity indicators
      const attachmentTable = page.locator('table').filter({ hasText: 'Name' }).first();
      const tableContent = await attachmentTable.textContent() || '';

      // Should have some form of validity indicator (🟢, 🔴, ✓, ⚠️, "Valid", "Invalid")
      const hasValidityIndicator = tableContent.includes('✓') ||
        tableContent.includes('⚠') ||
        tableContent.includes('Valid') ||
        tableContent.includes('Invalid') ||
        tableContent.includes('🟢') ||
        tableContent.includes('🔴');

      expect(hasValidityIndicator).toBe(true);
    }
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #11: Recommendation doesn't adapt to own findings
  // Source: QA Finding #11, Severity P0
  // ─────────────────────────────────────────────────────────────

  test('Finding-11: When confidence is Low, recommendation is not unconditional Yes', async ({ page }) => {
    // Open Full Analysis to check confidence levels
    await page.getByRole('button', { name: 'View Full Analysis' }).click();
    await page.waitForTimeout(5000);

    const modalContent = await page.locator('[class*="modal"], [role="dialog"]').textContent() || '';

    // Find questions where Confidence = Low
    const hasLowConfidence = modalContent.includes('Low');

    if (hasLowConfidence) {
      // Check if there's also an unconditional "Yes" suggested response
      // Parse: look for "Suggested Response: Yes" near "Confidence" sections marked Low
      const sections = modalContent.split(/\d+\./); // Split by question numbers

      for (const section of sections) {
        if (section.includes('Low') && section.includes('Confidence')) {
          // This question has Low confidence
          const suggestedResponse = section.match(/Suggested Response:\s*(\w+)/);
          if (suggestedResponse) {
            const response = suggestedResponse[1];
            // Should NOT be unconditional "Yes" when confidence is Low
            if (response === 'Yes') {
              // Check if it's conditional
              const isConditional = section.includes('conditional') ||
                section.includes('CONDITIONAL') ||
                section.includes('⚠️');
              expect(isConditional).toBe(true);
            }
          }
        }
      }
    }

    await page.keyboard.press('Escape');
  });

  // ─────────────────────────────────────────────────────────────
  // FINDING #12: Evidence validation only on manual Re-analyze
  // Source: QA Finding #12, Severity P0
  // Note: This is a destructive test — only run on PM-approved reviews
  // ─────────────────────────────────────────────────────────────

  test.skip('Finding-12: Evidence validation triggers on submit attempt (not just Re-analyze)', async ({ page }) => {
    // DESTRUCTIVE TEST — skip by default
    // Uncomment test.skip → test when running on approved test review

    // Attach a file (without clicking Re-analyze)
    await page.getByRole('button', { name: 'Add attachment' }).click();
    await page.waitForTimeout(2000);

    // Fill attachment name with something obviously wrong
    await page.getByLabel('Name').fill('Random Test File');
    await page.getByLabel('Description').fill('Test file not related to control');

    // Upload a file
    const fileInput = page.locator('input[type="file"]');
    await fileInput.setInputFiles('docs/qa-test-files/random-evidence.pdf');
    await page.waitForTimeout(3000);

    // DO NOT click Re-analyze — that's the bug
    // Instead, attempt to click Submit
    const submitButton = page.getByRole('button', { name: 'Submit' });

    // Assert: Submit should either be blocked OR show a warning about invalid evidence
    // Current bug: Submit proceeds with no warning
    const isBlocked = await submitButton.isDisabled();
    if (!isBlocked) {
      // If not blocked, at minimum there should be a warning visible
      const pageText = await page.textContent('body') || '';
      const hasEvidenceWarning = pageText.includes('invalid') ||
        pageText.includes('evidence issue') ||
        pageText.includes('validate') ||
        pageText.includes('⚠️');

      expect(hasEvidenceWarning).toBe(true);
    }
  });
});
